title: Xylen's Dashboard
email: priyanshudeb3@gmail.com
description: Personal homepage for my random stuff
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://debxylen.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: debxylen
github_username:  debxylen

collections:
  posts:
    output: true
